# Generated by Django 6.1.1 on 2026-09-10 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_movimentacaofidelidade_notificacaolog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoAssinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('preco_mensal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cortes_por_mes', models.PositiveIntegerField(default=2)),
                ('inclui_barba', models.BooleanField(default=False)),
                ('destaque', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='agendamento',
            name='checkin_realizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='em_atendimento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='metodo_pagamento',
            field=models.CharField(choices=[('local', 'Pagar no Salão'), ('pix_sinal', 'Pix (Sinal de R$ 10,00)'), ('pix_total', 'Pix (Valor Total)')], default='local', max_length=20),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='status_pagamento',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('reembolsado', 'Reembolsado')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo_indicacao',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='saldo_creditos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='agendamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_produtos', to='website.agendamento'),
        ),
        migrations.AlterField(
            model_name='notificacaolog',
            name='tipo',
            field=models.CharField(choices=[('confirmacao', 'Confirmação'), ('lembrete', 'Lembrete'), ('agradecimento', 'Agradecimento'), ('fila_espera', 'Fila de Espera')], max_length=20),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.IntegerField(default=10),
        ),
        migrations.CreateModel(
            name='BloqueioHorarioBarbeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField(blank=True, null=True)),
                ('dia_inteiro', models.BooleanField(default=False)),
                ('motivo', models.CharField(default='Indisponível / Folga', max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('barbeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios', to='website.barbeiro')),
            ],
        ),
        migrations.CreateModel(
            name='FilaEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_desejada', models.DateField()),
                ('turno', models.CharField(choices=[('qualquer', 'Qualquer Horário'), ('manha', 'Manhã (08h às 12h)'), ('tarde', 'Tarde (12h às 18h)'), ('noite', 'Noite (18h às 21h)')], default='qualquer', max_length=20)),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('notificado', 'Notificado'), ('atendido', 'Atendido'), ('cancelado', 'Cancelado')], default='aguardando', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('barbeiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fila_espera', to='website.barbeiro')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes_fila', to='website.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='AssinaturaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('suspensa', 'Suspensa'), ('cancelada', 'Cancelada')], default='ativa', max_length=20)),
                ('cortes_usados_mes', models.PositiveIntegerField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='website.cliente')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assinantes', to='website.planoassinatura')),
            ],
        ),
        migrations.CreateModel(
            name='FichaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estilo_corte', models.CharField(blank=True, max_length=200, null=True)),
                ('produtos_preferidos', models.CharField(blank=True, max_length=200, null=True)),
                ('observacoes_tecnicas', models.TextField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('barbeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_preenchidas', to='website.barbeiro')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_tecnicas', to='website.cliente')),
            ],
            options={
                'unique_together': {('cliente', 'barbeiro')},
            },
        ),
    ]
