# Generated by Django 6.1.1 on 2026-09-10 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_planoassinatura_agendamento_checkin_realizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planoassinatura',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='planoassinatura',
            name='limite_mensal',
            field=models.PositiveIntegerField(blank=True, default=4, null=True),
        ),
        migrations.AddField(
            model_name='planoassinatura',
            name='modalidade',
            field=models.CharField(choices=[('limitado', 'Limitado'), ('ilimitado', 'Ilimitado')], default='limitado', max_length=20),
        ),
        migrations.AddField(
            model_name='planoassinatura',
            name='servicos_inclusos',
            field=models.ManyToManyField(blank=True, related_name='planos_inclusos', to='website.servico'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='metodo_pagamento',
            field=models.CharField(choices=[('pix', 'PIX'), ('cartao', 'Cartão'), ('dinheiro', 'Dinheiro'), ('local', 'Pagar no Salão'), ('pix_sinal', 'Pix (Sinal)'), ('pix_total', 'Pix (Valor Total)')], default='local', max_length=20),
        ),
        migrations.AlterField(
            model_name='planoassinatura',
            name='cortes_por_mes',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.CreateModel(
            name='ItemAgendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duracao_minutos', models.PositiveIntegerField(default=30)),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='website.agendamento')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.servico')),
            ],
        ),
    ]
